# -*- coding: utf-8 -*-
"""Install Agent-Reach's SKILL.md into LAAP's skills directory.

Agent-Reach ships a SKILL.md describing how agents should call upstream
tools (curl https://r.jina.ai/URL, gh repo view, yt-dlp, mcporter, etc.).
We copy that file plus the references/ directory into LAAP's skills
folder so LAAP's SkillManager can surface the capability to the PSI
kernel and the agent's system prompt.

Idempotent: re-runs overwrite the existing skill files in place.
"""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path
from typing import Optional

logger = logging.getLogger("laap.integrations.agent_reach.skill_loader")

# LAAP's user skills directory (matches laap/skills/loader.py)
LAAP_SKILLS_DIR = Path.home() / ".laap" / "skills"
LAAP_AGENT_REACH_DIR = LAAP_SKILLS_DIR / "agent_reach"


def install_skill(force: bool = True) -> str:
    """Install Agent-Reach SKILL.md into LAAP's skills directory.

    Args:
        force: If False and the destination exists, do nothing.

    Returns:
        Status string: "installed" | "preserved" | "error: <msg>"
    """
    try:
        # Locate Agent-Reach's bundled skill dir (installed package)
        skill_src_dir = _find_agent_reach_skill_dir()
        if not skill_src_dir:
            return "error: agent_reach.skill package not found"

        if not force and LAAP_AGENT_REACH_DIR.exists():
            return "preserved"

        LAAP_AGENT_REACH_DIR.mkdir(parents=True, exist_ok=True)

        # Copy SKILL.md (prefer Chinese version, fallback to English)
        skill_md_src = skill_src_dir / "SKILL.md"
        skill_md_en = skill_src_dir / "SKILL_en.md"
        if not skill_md_src.exists() and skill_md_en.exists():
            skill_md_src = skill_md_en
        if skill_md_src.exists():
            shutil.copy2(skill_md_src, LAAP_AGENT_REACH_DIR / "SKILL.md")

        # Copy references/ directory if present
        refs_src = skill_src_dir / "references"
        refs_dst = LAAP_AGENT_REACH_DIR / "references"
        if refs_src.is_dir():
            if refs_dst.exists():
                shutil.rmtree(refs_dst)
            shutil.copytree(refs_src, refs_dst)

        # Drop a tiny Python shim so LAAP's SkillManager (which only
        # loads .py files) picks up the skill.
        shim = LAAP_AGENT_REACH_DIR / "agent_reach.py"
        shim.write_text(_SKILL_SHIM, encoding="utf-8")

        logger.info("Agent-Reach skill installed at %s", LAAP_AGENT_REACH_DIR)
        return "installed"
    except Exception as e:
        logger.error("Failed to install Agent-Reach skill: %s", e)
        return f"error: {e}"


def uninstall_skill() -> str:
    """Remove Agent-Reach skill from LAAP's skills directory."""
    try:
        if LAAP_AGENT_REACH_DIR.exists():
            shutil.rmtree(LAAP_AGENT_REACH_DIR)
            logger.info("Agent-Reach skill removed from %s", LAAP_AGENT_REACH_DIR)
            return "removed"
        return "not_present"
    except Exception as e:
        return f"error: {e}"


def _find_agent_reach_skill_dir() -> Optional[Path]:
    """Locate the bundled skill/ folder inside the installed agent_reach package."""
    try:
        import importlib.resources as ir
        # Try via Traversable API (Python 3.9+)
        root = ir.files("agent_reach")
        skill_dir = root.joinpath("skill")
        # Convert to a concrete Path for shutil operations
        try:
            return Path(str(skill_dir))
        except Exception:
            return None
    except Exception:
        # Fallback: walk site-packages for the package
        try:
            import agent_reach
            pkg_root = Path(agent_reach.__file__).resolve().parent
            candidate = pkg_root / "skill"
            if candidate.is_dir():
                return candidate
        except Exception:
            pass
    return None


# Skill shim: makes Agent-Reach discoverable by LAAP's SkillManager
# (which scans for *.py files in skills/). The shim re-exports the
# bridge so skill consumers can call it directly.
_SKILL_SHIM = '''"""LAAP Skill: Agent-Reach — Internet access layer.

Auto-generated by laap.integrations.agent_reach.skill_loader.
Wraps the bundled SKILL.md for LAAP's SkillManager discovery.
"""
__description__ = "互联网接入层：15+ 平台（YouTube/Twitter/Reddit/GitHub/B站/小红书等）的搜索与读取能力"
__version__ = "1.5.0"
__author__ = "Agent-Reach + LAAP"
__category__ = "internet"

from laap.integrations.agent_reach import AgentReachBridge

_bridge = AgentReachBridge()


def skill_status(**kwargs) -> str:
    """Return a one-line status of Agent-Reach channels."""
    summary = _bridge.summary()
    if not summary.get("available"):
        return f"Agent-Reach unavailable: {summary.get('error', 'unknown')}"
    return (
        f"Agent-Reach v{summary.get('version', '?')}: "
        f"{summary['ok']}/{summary['total_channels']} channels active "
        f"({summary['warn']} warn, {summary['off']} off)"
    )


def skill_doctor(**kwargs) -> str:
    """Return the full Agent-Reach doctor report."""
    return _bridge.doctor_report()


def tool_reach_read(url: str = "", **kwargs) -> str:
    """Read any URL via Agent-Reach (Jina Reader)."""
    if not url:
        return "Error: url parameter required"
    return _bridge.read_url(url)


def tool_reach_search(query: str = "", **kwargs) -> str:
    """Semantic search via Agent-Reach (Exa + mcporter)."""
    if not query:
        return "Error: query parameter required"
    return _bridge.search(query)
'''
